import { Project } from "./types";

// Reference "today" for the demo dataset.
export const TODAY = new Date("2026-05-28T00:00:00Z");

// Self-contained seed portfolio. In production this layer would be replaced by
// ERP / PMO integrations (see README "Integration Requirements").
export const projects: Project[] = [
  {
    id: "PRJ-001",
    code: "DXB-CORE",
    name: "Core Banking Modernization",
    description:
      "Replace legacy core banking platform with a cloud-native microservices stack.",
    subsidiary: "Gulf Holdings",
    businessUnit: "Digital",
    country: "UAE",
    manager: "Layla Hassan",
    status: "In Progress",
    priority: "High",
    budget: 4200000,
    actualCost: 3650000,
    progress: 62,
    startDate: "2024-09-01",
    plannedEndDate: "2026-06-30",
    milestones: [
      { id: "M1", name: "Discovery & Architecture", dueDate: "2024-12-15", status: "Done", completion: 100 },
      { id: "M2", name: "Account Services Migration", dueDate: "2025-08-30", status: "Done", completion: 100 },
      { id: "M3", name: "Payments Cutover", dueDate: "2026-04-30", status: "In Progress", completion: 55 },
      { id: "M4", name: "Decommission Legacy", dueDate: "2026-06-30", status: "Pending", completion: 0 },
    ],
    risks: [
      { id: "R1", description: "Data migration integrity for 2M accounts", severity: "High", likelihood: 0.4, mitigation: "Dual-run reconciliation", open: true },
      { id: "R2", description: "Vendor SLA on payment gateway", severity: "Medium", likelihood: 0.3, mitigation: "Contractual penalties", open: true },
    ],
    approvals: [
      { level: 1, role: "PMO", approver: "PMO Board", decision: "Approved", comment: "Aligned to roadmap", decidedAt: "2024-08-10" },
      { level: 2, role: "CDO Office", approver: "Chief Digital Office", decision: "Approved", comment: "Go", decidedAt: "2024-08-20" },
    ],
  },
  {
    id: "PRJ-002",
    code: "RUH-DATA",
    name: "Enterprise Data Lakehouse",
    description: "Unified analytics lakehouse consolidating ERP, CRM and IoT data.",
    subsidiary: "Levant Group",
    businessUnit: "Digital",
    country: "Saudi Arabia",
    manager: "Omar Al-Farsi",
    status: "Delayed",
    priority: "High",
    budget: 2800000,
    actualCost: 2950000,
    progress: 48,
    startDate: "2024-11-01",
    plannedEndDate: "2025-12-31",
    milestones: [
      { id: "M1", name: "Ingestion Framework", dueDate: "2025-04-30", status: "Done", completion: 100 },
      { id: "M2", name: "Governance & Catalog", dueDate: "2025-09-30", status: "Missed", completion: 60 },
      { id: "M3", name: "Self-Service BI", dueDate: "2025-12-31", status: "In Progress", completion: 30 },
    ],
    risks: [
      { id: "R1", description: "Scope creep from 6 source systems", severity: "Critical", likelihood: 0.7, mitigation: "Change control board", open: true },
      { id: "R2", description: "Data steward availability", severity: "High", likelihood: 0.5, mitigation: "Backfill contractors", open: true },
    ],
    approvals: [
      { level: 1, role: "PMO", approver: "PMO Board", decision: "Approved", decidedAt: "2024-10-05" },
      { level: 2, role: "CDO Office", approver: "Chief Digital Office", decision: "Approved", decidedAt: "2024-10-18" },
    ],
  },
  {
    id: "PRJ-003",
    code: "CAI-CX",
    name: "Customer Experience Portal",
    description: "Omnichannel self-service portal for retail customers.",
    subsidiary: "Levant Group",
    businessUnit: "Operations",
    country: "Egypt",
    manager: "Nourhan Adel",
    status: "In Progress",
    priority: "Medium",
    budget: 1200000,
    actualCost: 540000,
    progress: 51,
    startDate: "2025-02-01",
    plannedEndDate: "2026-02-28",
    milestones: [
      { id: "M1", name: "UX Research", dueDate: "2025-04-15", status: "Done", completion: 100 },
      { id: "M2", name: "MVP Launch", dueDate: "2025-11-30", status: "Done", completion: 100 },
      { id: "M3", name: "Mobile Rollout", dueDate: "2026-02-28", status: "In Progress", completion: 40 },
    ],
    risks: [
      { id: "R1", description: "Localization (Arabic/English) QA", severity: "Low", likelihood: 0.2, mitigation: "Automated i18n tests", open: true },
    ],
    approvals: [
      { level: 1, role: "PMO", approver: "PMO Board", decision: "Approved", decidedAt: "2025-01-12" },
      { level: 2, role: "Subsidiary Manager", approver: "Egypt GM", decision: "Approved", decidedAt: "2025-01-20" },
    ],
  },
  {
    id: "PRJ-004",
    code: "LON-RISK",
    name: "Regulatory Risk Engine",
    description: "Real-time compliance and AML monitoring engine.",
    subsidiary: "Europe Ltd",
    businessUnit: "Finance",
    country: "UK",
    manager: "James Whitfield",
    status: "In Progress",
    priority: "High",
    budget: 3100000,
    actualCost: 1850000,
    progress: 58,
    startDate: "2025-01-15",
    plannedEndDate: "2026-09-30",
    milestones: [
      { id: "M1", name: "Rules Engine Core", dueDate: "2025-07-31", status: "Done", completion: 100 },
      { id: "M2", name: "Transaction Monitoring", dueDate: "2026-03-31", status: "In Progress", completion: 65 },
      { id: "M3", name: "Regulatory Reporting", dueDate: "2026-09-30", status: "Pending", completion: 0 },
    ],
    risks: [
      { id: "R1", description: "Changing FCA reporting standards", severity: "High", likelihood: 0.45, mitigation: "Configurable rule packs", open: true },
    ],
    approvals: [
      { level: 1, role: "PMO", approver: "PMO Board", decision: "Approved", decidedAt: "2024-12-15" },
      { level: 2, role: "CDO Office", approver: "Chief Digital Office", decision: "Approved", decidedAt: "2025-01-05" },
    ],
  },
  {
    id: "PRJ-005",
    code: "BLR-AIOPS",
    name: "AIOps Observability Platform",
    description: "ML-driven anomaly detection across cloud infrastructure.",
    subsidiary: "Asia Pacific Co",
    businessUnit: "Infrastructure",
    country: "India",
    manager: "Priya Nair",
    status: "In Progress",
    priority: "Medium",
    budget: 1500000,
    actualCost: 1410000,
    progress: 44,
    startDate: "2025-03-01",
    plannedEndDate: "2026-04-30",
    milestones: [
      { id: "M1", name: "Telemetry Pipeline", dueDate: "2025-08-31", status: "Done", completion: 100 },
      { id: "M2", name: "Anomaly Models", dueDate: "2026-01-31", status: "Missed", completion: 50 },
      { id: "M3", name: "Auto-Remediation", dueDate: "2026-04-30", status: "Pending", completion: 0 },
    ],
    risks: [
      { id: "R1", description: "Model false-positive rate", severity: "Medium", likelihood: 0.5, mitigation: "Human-in-the-loop tuning", open: true },
      { id: "R2", description: "Cloud cost overrun on training", severity: "High", likelihood: 0.55, mitigation: "Spot instances + budget alerts", open: true },
    ],
    approvals: [
      { level: 1, role: "PMO", approver: "PMO Board", decision: "Approved", decidedAt: "2025-02-10" },
    ],
  },
  {
    id: "PRJ-006",
    code: "SGP-PAY",
    name: "Cross-Border Payments Hub",
    description: "Low-latency multi-currency settlement hub for APAC.",
    subsidiary: "Asia Pacific Co",
    businessUnit: "Digital",
    country: "Singapore",
    manager: "Wei Chen",
    status: "Completed",
    priority: "High",
    budget: 2600000,
    actualCost: 2480000,
    progress: 100,
    startDate: "2024-06-01",
    plannedEndDate: "2025-12-15",
    milestones: [
      { id: "M1", name: "Settlement Core", dueDate: "2025-02-28", status: "Done", completion: 100 },
      { id: "M2", name: "FX Integration", dueDate: "2025-08-31", status: "Done", completion: 100 },
      { id: "M3", name: "Go-Live", dueDate: "2025-12-15", status: "Done", completion: 100 },
    ],
    risks: [],
    approvals: [
      { level: 1, role: "PMO", approver: "PMO Board", decision: "Approved", decidedAt: "2024-05-10" },
      { level: 2, role: "CDO Office", approver: "Chief Digital Office", decision: "Approved", decidedAt: "2024-05-22" },
    ],
  },
  {
    id: "PRJ-007",
    code: "DXB-HR",
    name: "HR Workforce Analytics",
    description: "Predictive attrition and workforce planning suite.",
    subsidiary: "Gulf Holdings",
    businessUnit: "Operations",
    country: "UAE",
    manager: "Fatima Noor",
    status: "Planning",
    priority: "Low",
    budget: 700000,
    actualCost: 45000,
    progress: 8,
    startDate: "2026-04-01",
    plannedEndDate: "2026-12-31",
    milestones: [
      { id: "M1", name: "Requirements", dueDate: "2026-06-30", status: "In Progress", completion: 35 },
      { id: "M2", name: "Data Integration", dueDate: "2026-09-30", status: "Pending", completion: 0 },
    ],
    risks: [
      { id: "R1", description: "HR data privacy (PII) handling", severity: "Medium", likelihood: 0.3, mitigation: "Anonymization + DPIA", open: true },
    ],
    approvals: [
      { level: 1, role: "PMO", approver: "PMO Board", decision: "Pending" },
      { level: 2, role: "Subsidiary Manager", approver: "UAE GM", decision: "Pending" },
    ],
  },
  {
    id: "PRJ-008",
    code: "RUH-IOT",
    name: "Smart Facilities IoT",
    description: "Energy optimization across 40 facilities using IoT sensors.",
    subsidiary: "Levant Group",
    businessUnit: "Infrastructure",
    country: "Saudi Arabia",
    manager: "Khalid Mansour",
    status: "Delayed",
    priority: "Medium",
    budget: 1900000,
    actualCost: 2210000,
    progress: 70,
    startDate: "2024-10-01",
    plannedEndDate: "2025-11-30",
    milestones: [
      { id: "M1", name: "Sensor Rollout", dueDate: "2025-05-31", status: "Done", completion: 100 },
      { id: "M2", name: "Edge Gateway", dueDate: "2025-09-30", status: "Done", completion: 100 },
      { id: "M3", name: "Optimization Engine", dueDate: "2025-11-30", status: "In Progress", completion: 60 },
    ],
    risks: [
      { id: "R1", description: "Sensor hardware supply delays", severity: "High", likelihood: 0.6, mitigation: "Dual suppliers", open: true },
      { id: "R2", description: "Integration with legacy BMS", severity: "Medium", likelihood: 0.4, mitigation: "Protocol adapters", open: false },
    ],
    approvals: [
      { level: 1, role: "PMO", approver: "PMO Board", decision: "Approved", decidedAt: "2024-09-05" },
      { level: 2, role: "Subsidiary Manager", approver: "KSA GM", decision: "Approved", decidedAt: "2024-09-18" },
    ],
  },
  {
    id: "PRJ-009",
    code: "LON-ESG",
    name: "ESG Reporting Platform",
    description: "Automated sustainability and ESG disclosure reporting.",
    subsidiary: "Europe Ltd",
    businessUnit: "Finance",
    country: "UK",
    manager: "Sophie Bennett",
    status: "Completed",
    priority: "Medium",
    budget: 900000,
    actualCost: 870000,
    progress: 100,
    startDate: "2024-08-01",
    plannedEndDate: "2025-10-31",
    milestones: [
      { id: "M1", name: "Data Taxonomy", dueDate: "2025-01-31", status: "Done", completion: 100 },
      { id: "M2", name: "Reporting Engine", dueDate: "2025-07-31", status: "Done", completion: 100 },
      { id: "M3", name: "Audit Sign-off", dueDate: "2025-10-31", status: "Done", completion: 100 },
    ],
    risks: [],
    approvals: [
      { level: 1, role: "PMO", approver: "PMO Board", decision: "Approved", decidedAt: "2024-07-10" },
    ],
  },
  {
    id: "PRJ-010",
    code: "BLR-RND",
    name: "GenAI Knowledge Assistant",
    description: "Internal RAG assistant over policy and engineering knowledge.",
    subsidiary: "Asia Pacific Co",
    businessUnit: "R&D",
    country: "India",
    manager: "Arjun Mehta",
    status: "In Progress",
    priority: "High",
    budget: 1100000,
    actualCost: 1320000,
    progress: 40,
    startDate: "2025-05-01",
    plannedEndDate: "2026-05-31",
    milestones: [
      { id: "M1", name: "Knowledge Ingestion", dueDate: "2025-09-30", status: "Done", completion: 100 },
      { id: "M2", name: "RAG Pipeline", dueDate: "2026-01-31", status: "Missed", completion: 45 },
      { id: "M3", name: "Enterprise Rollout", dueDate: "2026-05-31", status: "Pending", completion: 0 },
    ],
    risks: [
      { id: "R1", description: "Hallucination / answer quality", severity: "High", likelihood: 0.5, mitigation: "Grounded citations + eval suite", open: true },
      { id: "R2", description: "Token cost at scale", severity: "Medium", likelihood: 0.5, mitigation: "Caching + smaller models", open: true },
    ],
    approvals: [
      { level: 1, role: "PMO", approver: "PMO Board", decision: "Approved", decidedAt: "2025-04-10" },
      { level: 2, role: "CDO Office", approver: "Chief Digital Office", decision: "Approved", decidedAt: "2025-04-20" },
    ],
  },
  {
    id: "PRJ-011",
    code: "SGP-CLOUD",
    name: "Cloud Migration Wave 2",
    description: "Lift-and-shift plus re-platform of 60 legacy workloads.",
    subsidiary: "Asia Pacific Co",
    businessUnit: "Infrastructure",
    country: "Singapore",
    manager: "Grace Lim",
    status: "In Progress",
    priority: "Medium",
    budget: 2000000,
    actualCost: 980000,
    progress: 55,
    startDate: "2025-06-01",
    plannedEndDate: "2026-07-31",
    milestones: [
      { id: "M1", name: "Landing Zone", dueDate: "2025-09-30", status: "Done", completion: 100 },
      { id: "M2", name: "Wave 2a Migration", dueDate: "2026-02-28", status: "Done", completion: 100 },
      { id: "M3", name: "Wave 2b Migration", dueDate: "2026-07-31", status: "In Progress", completion: 35 },
    ],
    risks: [
      { id: "R1", description: "Undocumented app dependencies", severity: "Medium", likelihood: 0.45, mitigation: "Dependency mapping tool", open: true },
    ],
    approvals: [
      { level: 1, role: "PMO", approver: "PMO Board", decision: "Approved", decidedAt: "2025-05-10" },
    ],
  },
  {
    id: "PRJ-012",
    code: "CAI-FIN",
    name: "Finance Consolidation Suite",
    description: "Group-wide financial consolidation and IFRS reporting.",
    subsidiary: "Levant Group",
    businessUnit: "Finance",
    country: "Egypt",
    manager: "Yousef Ibrahim",
    status: "On Hold",
    priority: "Low",
    budget: 800000,
    actualCost: 260000,
    progress: 22,
    startDate: "2025-01-01",
    plannedEndDate: "2026-03-31",
    milestones: [
      { id: "M1", name: "Chart of Accounts Mapping", dueDate: "2025-05-31", status: "Done", completion: 100 },
      { id: "M2", name: "Consolidation Logic", dueDate: "2025-12-31", status: "Pending", completion: 10 },
    ],
    risks: [
      { id: "R1", description: "Budget freeze pending reorg", severity: "Medium", likelihood: 0.6, mitigation: "Re-baseline on resume", open: true },
    ],
    approvals: [
      { level: 1, role: "PMO", approver: "PMO Board", decision: "Approved", decidedAt: "2024-12-10" },
      { level: 2, role: "Subsidiary Manager", approver: "Egypt GM", decision: "Rejected", comment: "Deferred to next FY", decidedAt: "2025-09-01" },
    ],
  },
  {
    id: "PRJ-013",
    code: "DXB-SEC",
    name: "Zero-Trust Security Program",
    description: "Identity-centric zero-trust architecture rollout.",
    subsidiary: "Gulf Holdings",
    businessUnit: "Infrastructure",
    country: "UAE",
    manager: "Hind Saleh",
    status: "In Progress",
    priority: "High",
    budget: 2400000,
    actualCost: 2050000,
    progress: 68,
    startDate: "2024-12-01",
    plannedEndDate: "2026-05-31",
    milestones: [
      { id: "M1", name: "Identity Platform", dueDate: "2025-06-30", status: "Done", completion: 100 },
      { id: "M2", name: "Microsegmentation", dueDate: "2026-02-28", status: "Done", completion: 100 },
      { id: "M3", name: "Continuous Verification", dueDate: "2026-05-31", status: "In Progress", completion: 70 },
    ],
    risks: [
      { id: "R1", description: "Legacy app MFA incompatibility", severity: "Medium", likelihood: 0.4, mitigation: "Proxy-based MFA", open: true },
    ],
    approvals: [
      { level: 1, role: "PMO", approver: "PMO Board", decision: "Approved", decidedAt: "2024-11-05" },
      { level: 2, role: "CDO Office", approver: "Chief Digital Office", decision: "Approved", decidedAt: "2024-11-18" },
    ],
  },
  {
    id: "PRJ-014",
    code: "LON-MKT",
    name: "Marketing Personalization Engine",
    description: "Real-time personalization and next-best-action engine.",
    subsidiary: "Europe Ltd",
    businessUnit: "Digital",
    country: "UK",
    manager: "Daniel Cole",
    status: "Delayed",
    priority: "Medium",
    budget: 1300000,
    actualCost: 1500000,
    progress: 52,
    startDate: "2024-10-15",
    plannedEndDate: "2025-10-31",
    milestones: [
      { id: "M1", name: "CDP Integration", dueDate: "2025-03-31", status: "Done", completion: 100 },
      { id: "M2", name: "Recommendation Models", dueDate: "2025-08-31", status: "Missed", completion: 55 },
      { id: "M3", name: "Channel Activation", dueDate: "2025-10-31", status: "In Progress", completion: 25 },
    ],
    risks: [
      { id: "R1", description: "Consent / GDPR constraints on targeting", severity: "High", likelihood: 0.5, mitigation: "Consent-aware feature store", open: true },
    ],
    approvals: [
      { level: 1, role: "PMO", approver: "PMO Board", decision: "Approved", decidedAt: "2024-09-20" },
    ],
  },
];
